import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as apigatewayv2 from 'aws-cdk-lib/aws-apigatewayv2';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import { SITE_ORIGIN, BETA_SITE_ORIGIN, SES_FROM_ADDRESS, SES_TO_ADDRESS } from './config';

export interface FanningSnsStackProps extends cdk.StackProps {
  stage: 'prod' | 'beta';
}

/**
 * Generated by `cdk migrate --from-stack --stack-name fanning-sns` against the
 * live CloudFormation template, then hand-cleaned. For `stage: 'prod'`, every
 * logical ID and physical name below matches the deployed stack exactly, so
 * `cdk deploy` is a normal in-place stack update -- no `cdk import` required.
 * Do not rename constructs or change prod's physical names; that would make
 * CloudFormation replace the underlying resource.
 *
 * `stage: 'beta'` deploys this exact same shape as an entirely separate,
 * brand-new stack -- its own table, queue, topic, Lambdas, and API, wired
 * only to the beta site origin. Nothing is shared with prod.
 */
export class FanningSnsStack extends cdk.Stack {
  public readonly apiEndpoint: string;

  constructor(scope: Construct, id: string, props: FanningSnsStackProps) {
    super(scope, id, props);

    const { stage } = props;
    const namePrefix = stage === 'prod' ? 'fanningsns' : 'fanningsns-beta';
    const origin = stage === 'prod' ? SITE_ORIGIN : BETA_SITE_ORIGIN;
    // Prod's table was imported holding real data, so it keeps the RETAIN
    // safety net a stack delete can't override; beta's is a fresh resource
    // with nothing at stake, so a destroy there is genuinely complete.
    const removalPolicy = stage === 'prod' ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY;

    const deliveryLogTable = new dynamodb.CfnTable(this, 'DeliveryLogTable', {
      billingMode: 'PAY_PER_REQUEST',
      attributeDefinitions: [
        { attributeName: 'messageId', attributeType: 'S' },
        { attributeName: 'subscriber', attributeType: 'S' },
        { attributeName: 'gsiPk', attributeType: 'S' },
        { attributeName: 'triggeredAt', attributeType: 'S' },
      ],
      keySchema: [
        { attributeName: 'messageId', keyType: 'HASH' },
        { attributeName: 'subscriber', keyType: 'RANGE' },
      ],
      globalSecondaryIndexes: [
        {
          indexName: 'RecentIndex',
          keySchema: [
            { attributeName: 'gsiPk', keyType: 'HASH' },
            { attributeName: 'triggeredAt', keyType: 'RANGE' },
          ],
          projection: { projectionType: 'ALL' },
        },
      ],
      timeToLiveSpecification: { attributeName: 'ttl', enabled: true },
    });
    deliveryLogTable.applyRemovalPolicy(removalPolicy);

    const loggerDlq = new sqs.CfnQueue(this, 'LoggerDLQ', {
      messageRetentionPeriod: 345600, // 4 days
    });

    const notificationTopic = new sns.CfnTopic(this, 'NotificationTopic', {});

    const loggerFunctionRole = new iam.CfnRole(this, 'LoggerFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: [
        'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
        'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole',
      ],
      policies: [
        {
          policyName: 'LoggerFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: ['dynamodb:PutItem', 'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem'],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const loggerQueue = new sqs.CfnQueue(this, 'LoggerQueue', {
      messageRetentionPeriod: 86400, // 1 day
      redrivePolicy: { deadLetterTargetArn: loggerDlq.attrArn, maxReceiveCount: 3 },
    });

    const notifierFunctionRole = new iam.CfnRole(this, 'NotifierFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'NotifierFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: ['dynamodb:PutItem', 'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem'],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'NotifierFunctionRolePolicy1',
          policyDocument: { Statement: [{ Effect: 'Allow', Action: 'ses:SendEmail', Resource: '*' }] },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const publisherFunctionRole = new iam.CfnRole(this, 'PublisherFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'PublisherFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: ['sns:Publish'],
                Effect: 'Allow',
                Resource: `arn:${this.partition}:sns:${this.region}:${this.account}:${notificationTopic.attrTopicName}`,
              },
            ],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const recentFunctionRole = new iam.CfnRole(this, 'RecentFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'RecentFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: ['dynamodb:GetItem', 'dynamodb:Scan', 'dynamodb:Query', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable'],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${deliveryLogTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const functionCode: lambda.CfnFunction.CodeProperty = {
      s3Bucket: 'aws-sam-cli-managed-default-samclisourcebucket-h4mc9gkyohw4',
      s3Key: 'fanning-sns/69fec8b6775831ad95c8cf58624d206e',
    };

    const loggerFunction = new lambda.CfnFunction(this, 'LoggerFunction', {
      code: functionCode,
      functionName: `${namePrefix}-logger`,
      handler: 'log_handler.lambda_handler',
      memorySize: 128,
      role: loggerFunctionRole.attrArn,
      runtime: 'python3.13',
      timeout: 10,
      environment: { variables: { TABLE_NAME: deliveryLogTable.ref } },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    new sqs.CfnQueuePolicy(this, 'LoggerQueuePolicy', {
      queues: [loggerQueue.ref],
      policyDocument: {
        Statement: [
          {
            Effect: 'Allow',
            Principal: { Service: 'sns.amazonaws.com' },
            Action: 'sqs:SendMessage',
            Resource: loggerQueue.attrArn,
            Condition: { ArnEquals: { 'aws:SourceArn': notificationTopic.ref } },
          },
        ],
      },
    });

    new sns.CfnSubscription(this, 'LoggerQueueSubscription', {
      topicArn: notificationTopic.ref,
      protocol: 'sqs',
      endpoint: loggerQueue.attrArn,
    });

    const notifierFunction = new lambda.CfnFunction(this, 'NotifierFunction', {
      code: functionCode,
      functionName: `${namePrefix}-notifier`,
      handler: 'notify_handler.lambda_handler',
      memorySize: 128,
      role: notifierFunctionRole.attrArn,
      runtime: 'python3.13',
      timeout: 10,
      environment: {
        variables: { TABLE_NAME: deliveryLogTable.ref, ADMIN_EMAIL: SES_FROM_ADDRESS, SNS_TO_EMAIL: SES_TO_ADDRESS },
      },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const publisherFunction = new lambda.CfnFunction(this, 'PublisherFunction', {
      code: functionCode,
      functionName: `${namePrefix}-publisher`,
      handler: 'publish_handler.lambda_handler',
      memorySize: 128,
      role: publisherFunctionRole.attrArn,
      runtime: 'python3.13',
      timeout: 10,
      environment: { variables: { TOPIC_ARN: notificationTopic.ref, ALLOWED_ORIGIN: origin } },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const recentFunction = new lambda.CfnFunction(this, 'RecentFunction', {
      code: functionCode,
      functionName: `${namePrefix}-recent`,
      handler: 'recent_handler.lambda_handler',
      memorySize: 128,
      role: recentFunctionRole.attrArn,
      runtime: 'python3.13',
      timeout: 10,
      environment: { variables: { TABLE_NAME: deliveryLogTable.ref, ALLOWED_ORIGIN: origin } },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    new lambda.CfnEventSourceMapping(this, 'LoggerFunctionQueueTrigger', {
      batchSize: 5,
      eventSourceArn: loggerQueue.attrArn,
      functionName: loggerFunction.ref,
    });

    new lambda.CfnPermission(this, 'NotifierInvokePermission', {
      action: 'lambda:InvokeFunction',
      functionName: notifierFunction.ref,
      principal: 'sns.amazonaws.com',
      sourceArn: notificationTopic.ref,
    });

    new sns.CfnSubscription(this, 'NotifierSubscription', {
      topicArn: notificationTopic.ref,
      protocol: 'lambda',
      endpoint: notifierFunction.attrArn,
    });

    const notifyApi = new apigatewayv2.CfnApi(this, 'NotifyApi', {
      body: {
        info: { version: '1.0', title: this.stackName },
        paths: {
          '/notify/recent': {
            get: {
              'x-amazon-apigateway-integration': {
                httpMethod: 'POST',
                type: 'aws_proxy',
                uri: `arn:${this.partition}:apigateway:${this.region}:lambda:path/2015-03-31/functions/${recentFunction.attrArn}/invocations`,
                payloadFormatVersion: '2.0',
              },
              responses: {},
            },
          },
          '/notify': {
            post: {
              'x-amazon-apigateway-integration': {
                httpMethod: 'POST',
                type: 'aws_proxy',
                uri: `arn:${this.partition}:apigateway:${this.region}:lambda:path/2015-03-31/functions/${publisherFunction.attrArn}/invocations`,
                payloadFormatVersion: '2.0',
              },
              responses: {},
            },
          },
        },
        'x-amazon-apigateway-cors': {
          allowOrigins: [origin],
          allowHeaders: ['Content-Type'],
          allowMethods: ['GET', 'POST', 'OPTIONS'],
        },
        openapi: '3.0.1',
        tags: [{ name: 'httpapi:createdBy', 'x-amazon-apigateway-tag-value': 'SAM' }],
      },
    });
    // API Gateway rejects a top-level Tags property alongside an OpenAPI
    // Body definition outright ("Redundant fields... when Body is not
    // empty") -- confirmed by an actual failed deploy attempt. This
    // resource is the one exception to every other resource in this stack
    // getting the app-level Project/Stage tags.
    cdk.Tags.of(notifyApi).remove('Project');
    cdk.Tags.of(notifyApi).remove('Stage');

    new apigatewayv2.CfnStage(this, 'NotifyApiApiGatewayDefaultStage', {
      defaultRouteSettings: { throttlingRateLimit: 5, throttlingBurstLimit: 10 },
      apiId: notifyApi.ref,
      stageName: '$default',
      tags: { 'httpapi:createdBy': 'SAM' },
      autoDeploy: true,
    });

    new lambda.CfnPermission(this, 'PublisherFunctionNotifyPostPermission', {
      action: 'lambda:InvokeFunction',
      functionName: publisherFunction.ref,
      principal: 'apigateway.amazonaws.com',
      sourceArn: `arn:${this.partition}:execute-api:${this.region}:${this.account}:${notifyApi.ref}/*/POST/notify`,
    });

    new lambda.CfnPermission(this, 'RecentFunctionRecentGetPermission', {
      action: 'lambda:InvokeFunction',
      functionName: recentFunction.ref,
      principal: 'apigateway.amazonaws.com',
      sourceArn: `arn:${this.partition}:execute-api:${this.region}:${this.account}:${notifyApi.ref}/*/GET/notify/recent`,
    });

    this.apiEndpoint = `https://${notifyApi.ref}.execute-api.${this.region}.amazonaws.com`;

    new cdk.CfnOutput(this, 'NotifyApiEndpoint', {
      description: 'Value to paste into projects/sns-notification-fan-out/frontend/config.js as apiBase',
      value: this.apiEndpoint,
    });
    new cdk.CfnOutput(this, 'NotificationTopicArn', { value: notificationTopic.ref });
    new cdk.CfnOutput(this, 'DeliveryLogTableName', { value: deliveryLogTable.ref });
  }
}
