import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as apigatewayv2 from 'aws-cdk-lib/aws-apigatewayv2';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { SITE_ORIGIN, SES_FROM_ADDRESS, SES_TO_ADDRESS } from './config';

export interface LivePollStackProps extends cdk.StackProps {
  stage: 'prod' | 'beta';
}

/**
 * Generated by `cdk migrate --from-stack --stack-name live-poll` against the
 * live CloudFormation template, then hand-cleaned. For `stage: 'prod'`, every
 * logical ID and physical name below matches the deployed stack exactly, so
 * `cdk deploy` is a normal in-place stack update -- no `cdk import` required.
 * Do not rename constructs or change prod's physical names; that would make
 * CloudFormation replace the underlying resource.
 *
 * `stage: 'beta'` deploys this exact same shape as an entirely separate,
 * brand-new stack -- its own tables, WebSocket API, and Lambdas. Nothing is
 * shared with prod. This stack has no CORS to narrow (WebSocket, not a
 * browser-CORS-checked HTTP API), so `stage` only affects physical naming,
 * removal policy, and the email content's SITE_BASE_URL.
 */
export class LivePollStack extends cdk.Stack {
  public readonly webSocketUrl: string;

  constructor(scope: Construct, id: string, props: LivePollStackProps) {
    super(scope, id, props);

    const { stage } = props;
    const namePrefix = stage === 'prod' ? 'live-poll' : 'live-poll-beta';
    // Prod's tables were imported holding real data, so they keep the
    // RETAIN safety net a stack delete can't override; beta's are fresh
    // resources with nothing at stake, so a destroy there is genuinely
    // complete.
    const removalPolicy = stage === 'prod' ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY;

    const pollConnectionsTable = new dynamodb.CfnTable(this, 'PollConnectionsTable', {
      tableName: `${namePrefix}-connections`,
      billingMode: 'PAY_PER_REQUEST',
      attributeDefinitions: [{ attributeName: 'connectionId', attributeType: 'S' }],
      keySchema: [{ attributeName: 'connectionId', keyType: 'HASH' }],
    });
    pollConnectionsTable.applyRemovalPolicy(removalPolicy);

    const pollTalliesTable = new dynamodb.CfnTable(this, 'PollTalliesTable', {
      tableName: `${namePrefix}-tallies`,
      billingMode: 'PAY_PER_REQUEST',
      attributeDefinitions: [
        { attributeName: 'pollId', attributeType: 'S' },
        { attributeName: 'option', attributeType: 'S' },
      ],
      keySchema: [
        { attributeName: 'pollId', keyType: 'HASH' },
        { attributeName: 'option', keyType: 'RANGE' },
      ],
    });
    pollTalliesTable.applyRemovalPolicy(removalPolicy);

    const pollVotesTable = new dynamodb.CfnTable(this, 'PollVotesTable', {
      tableName: `${namePrefix}-votes`,
      billingMode: 'PAY_PER_REQUEST',
      attributeDefinitions: [
        { attributeName: 'pollId', attributeType: 'S' },
        { attributeName: 'voterId', attributeType: 'S' },
      ],
      keySchema: [
        { attributeName: 'pollId', keyType: 'HASH' },
        { attributeName: 'voterId', keyType: 'RANGE' },
      ],
    });
    pollVotesTable.applyRemovalPolicy(removalPolicy);

    const pollWebSocketApi = new apigatewayv2.CfnApi(this, 'PollWebSocketApi', {
      name: `${namePrefix}-ws`,
      protocolType: 'WEBSOCKET',
      routeSelectionExpression: '$request.body.action',
    });

    const pollConnectFunctionRole = new iam.CfnRole(this, 'PollConnectFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'PollConnectFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: [
                  'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:PutItem', 'dynamodb:Scan', 'dynamodb:Query',
                  'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable',
                  'dynamodb:ConditionCheckItem',
                ],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const pollDisconnectFunctionRole = new iam.CfnRole(this, 'PollDisconnectFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'PollDisconnectFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: [
                  'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:PutItem', 'dynamodb:Scan', 'dynamodb:Query',
                  'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable',
                  'dynamodb:ConditionCheckItem',
                ],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'PollDisconnectFunctionRolePolicy1',
          policyDocument: {
            Statement: [
              {
                Action: ['dynamodb:GetItem', 'dynamodb:Scan', 'dynamodb:Query', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable'],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollTalliesTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollTalliesTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'PollDisconnectFunctionRolePolicy2',
          policyDocument: {
            Statement: [{ Effect: 'Allow', Action: ['ses:SendEmail', 'ses:SendRawEmail'], Resource: '*' }],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const pollVoteFunctionRole = new iam.CfnRole(this, 'PollVoteFunctionRole', {
      assumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [
          { Action: ['sts:AssumeRole'], Effect: 'Allow', Principal: { Service: ['lambda.amazonaws.com'] } },
        ],
      },
      managedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
      policies: [
        {
          policyName: 'PollVoteFunctionRolePolicy0',
          policyDocument: {
            Statement: [
              {
                Action: [
                  'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:PutItem', 'dynamodb:Scan', 'dynamodb:Query',
                  'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable',
                  'dynamodb:ConditionCheckItem',
                ],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollVotesTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollVotesTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'PollVoteFunctionRolePolicy1',
          policyDocument: {
            Statement: [
              {
                Action: [
                  'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:PutItem', 'dynamodb:Scan', 'dynamodb:Query',
                  'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable',
                  'dynamodb:ConditionCheckItem',
                ],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollTalliesTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollTalliesTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'PollVoteFunctionRolePolicy2',
          policyDocument: {
            Statement: [
              {
                Action: [
                  'dynamodb:GetItem', 'dynamodb:DeleteItem', 'dynamodb:PutItem', 'dynamodb:Scan', 'dynamodb:Query',
                  'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:BatchGetItem', 'dynamodb:DescribeTable',
                  'dynamodb:ConditionCheckItem',
                ],
                Effect: 'Allow',
                Resource: [
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}`,
                  `arn:${this.partition}:dynamodb:${this.region}:${this.account}:table/${pollConnectionsTable.ref}/index/*`,
                ],
              },
            ],
          },
        },
        {
          policyName: 'PollVoteFunctionRolePolicy3',
          policyDocument: {
            Statement: [
              {
                Effect: 'Allow',
                Action: 'execute-api:ManageConnections',
                Resource: `arn:aws:execute-api:${this.region}:${this.account}:${pollWebSocketApi.ref}/prod/POST/@connections/*`,
              },
            ],
          },
        },
      ],
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    new apigatewayv2.CfnStage(this, 'PollWebSocketStage', {
      apiId: pollWebSocketApi.ref,
      stageName: 'prod',
      autoDeploy: true,
    });

    const functionCode: lambda.CfnFunction.CodeProperty = {
      s3Bucket: 'aws-sam-cli-managed-default-samclisourcebucket-h4mc9gkyohw4',
      s3Key: 'live-poll/4f1f6176be132ecf8aa5b3673872d398',
    };

    const pollConnectFunction = new lambda.CfnFunction(this, 'PollConnectFunction', {
      code: functionCode,
      handler: 'on_connect.lambda_handler',
      memorySize: 128,
      role: pollConnectFunctionRole.attrArn,
      runtime: 'python3.12',
      timeout: 10,
      environment: { variables: { CONNECTIONS_TABLE: pollConnectionsTable.ref } },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const pollDisconnectFunction = new lambda.CfnFunction(this, 'PollDisconnectFunction', {
      code: functionCode,
      handler: 'on_disconnect.lambda_handler',
      memorySize: 128,
      role: pollDisconnectFunctionRole.attrArn,
      runtime: 'python3.12',
      timeout: 10,
      environment: {
        variables: {
          CONNECTIONS_TABLE: pollConnectionsTable.ref,
          TALLIES_TABLE: pollTalliesTable.ref,
          SES_FROM_ADDRESS: SES_FROM_ADDRESS,
          SES_TO_ADDRESS: SES_TO_ADDRESS,
          // Email links always point at the real site, regardless of which
          // stage's backend generated the email.
          SITE_BASE_URL: SITE_ORIGIN,
        },
      },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const pollVoteFunction = new lambda.CfnFunction(this, 'PollVoteFunction', {
      code: functionCode,
      handler: 'vote_handler.lambda_handler',
      memorySize: 128,
      role: pollVoteFunctionRole.attrArn,
      runtime: 'python3.12',
      timeout: 10,
      environment: {
        variables: {
          VOTES_TABLE: pollVotesTable.ref,
          TALLIES_TABLE: pollTalliesTable.ref,
          CONNECTIONS_TABLE: pollConnectionsTable.ref,
          WEBSOCKET_ENDPOINT: `https://${pollWebSocketApi.ref}.execute-api.${this.region}.amazonaws.com/prod`,
        },
      },
      tags: [{ key: 'lambda:createdBy', value: 'SAM' }],
    });

    const connectIntegration = new apigatewayv2.CfnIntegration(this, 'ConnectIntegration', {
      apiId: pollWebSocketApi.ref,
      integrationType: 'AWS_PROXY',
      integrationUri: `arn:aws:apigateway:${this.region}:lambda:path/2015-03-31/functions/${pollConnectFunction.attrArn}/invocations`,
    });

    const disconnectIntegration = new apigatewayv2.CfnIntegration(this, 'DisconnectIntegration', {
      apiId: pollWebSocketApi.ref,
      integrationType: 'AWS_PROXY',
      integrationUri: `arn:aws:apigateway:${this.region}:lambda:path/2015-03-31/functions/${pollDisconnectFunction.attrArn}/invocations`,
    });

    new lambda.CfnPermission(this, 'PollConnectPermission', {
      action: 'lambda:InvokeFunction',
      functionName: pollConnectFunction.ref,
      principal: 'apigateway.amazonaws.com',
    });

    new lambda.CfnPermission(this, 'PollDisconnectPermission', {
      action: 'lambda:InvokeFunction',
      functionName: pollDisconnectFunction.ref,
      principal: 'apigateway.amazonaws.com',
    });

    new lambda.CfnPermission(this, 'PollVotePermission', {
      action: 'lambda:InvokeFunction',
      functionName: pollVoteFunction.ref,
      principal: 'apigateway.amazonaws.com',
    });

    const voteIntegration = new apigatewayv2.CfnIntegration(this, 'VoteIntegration', {
      apiId: pollWebSocketApi.ref,
      integrationType: 'AWS_PROXY',
      integrationUri: `arn:aws:apigateway:${this.region}:lambda:path/2015-03-31/functions/${pollVoteFunction.attrArn}/invocations`,
    });

    new apigatewayv2.CfnRoute(this, 'ConnectRoute', {
      apiId: pollWebSocketApi.ref,
      routeKey: '$connect',
      target: `integrations/${connectIntegration.ref}`,
    });

    new apigatewayv2.CfnRoute(this, 'DisconnectRoute', {
      apiId: pollWebSocketApi.ref,
      routeKey: '$disconnect',
      target: `integrations/${disconnectIntegration.ref}`,
    });

    new apigatewayv2.CfnRoute(this, 'SyncRoute', {
      apiId: pollWebSocketApi.ref,
      routeKey: 'sync',
      target: `integrations/${voteIntegration.ref}`,
    });

    new apigatewayv2.CfnRoute(this, 'VoteRoute', {
      apiId: pollWebSocketApi.ref,
      routeKey: 'vote',
      target: `integrations/${voteIntegration.ref}`,
    });

    this.webSocketUrl = `wss://${pollWebSocketApi.ref}.execute-api.${this.region}.amazonaws.com/prod`;

    new cdk.CfnOutput(this, 'PollWebSocketUrl', {
      description: 'WebSocket URL -- paste this into config.js as pollWsUrl.',
      value: this.webSocketUrl,
    });
  }
}
